
name: Auto Sync Simulation Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Simulation
        run: |
          chmod +x src/run_simulation.py
          python src/run_simulation.py
        
      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Auto-update simulation data $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
